# Generated by Django 2.0.13 on 2019-12-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oyoyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'およよ',
                'verbose_name_plural': 'およよ一覧',
            },
        ),
    ]
