# Generated by Django 2.0.13 on 2019-12-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosukoi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyoyo',
            name='app_status',
            field=models.CharField(choices=[('W', '承認待ち'), ('U', '更新承認済み'), ('B', '営業承認済み')], default='W', max_length=1, verbose_name='承認ステータス'),
        ),
    ]
