# Generated by Django 2.0.13 on 2019-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosukoi', '0002_oyoyo_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='oyoyo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
